dependencies {
	testIntegrationCompile group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testIntegrationCompile group: "org.hibernate", name: "hibernate-core", version: "5.5.3.Final"
	testIntegrationCompile group: "org.osgi", name: "osgi.core", version: "6.0.0"
	testIntegrationCompile group: "org.skyscreamer", name: "jsonassert", version: "1.2.3"
	testIntegrationCompile group: "org.springframework", name: "spring-tx", version: "4.3.22.RELEASE"
	testIntegrationCompile project(":apps:json-storage:json-storage-api")
	testIntegrationCompile project(":test:arquillian-extension-junit-bridge")
}