dependencies {
	testCompile group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testCompile group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	testCompile group: "junit", name: "junit", version: "4.12"
	testCompile project(":apps:portal-template:portal-template-api")
}