dependencies {
	testIntegrationCompile group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testIntegrationCompile group: "org.hibernate", name: "hibernate-core", version: "5.5.3.Final"
	testIntegrationCompile project(":apps:change-tracking:change-tracking-test-util")
	testIntegrationCompile project(":apps:journal:journal-api")
	testIntegrationCompile project(":test:arquillian-extension-junit-bridge")
}