dependencies {
	testIntegrationCompile group: "org.hibernate", name: "hibernate-core", version: "5.5.3.Final"
	testIntegrationCompile project(":apps:portal-lock:portal-lock-api")
	testIntegrationCompile project(":apps:portal-lock:portal-lock-service")
	testIntegrationCompile project(":test:arquillian-extension-junit-bridge")
}