dependencies {
	testCompile group: "com.liferay", name: "log4j-api", version: "2.13.2.LIFERAY-PATCHED-1"
	testCompile group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testCompile group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	testCompile project(":apps:petra:petra-log4j")
	testCompile project(":core:petra:petra-io")
	testCompile project(":core:petra:petra-string")
}